expiry-period-format: "&e&l[Thời hạn: %value%]"
expiry-date-format: "&e&l[HSD: %value%]"
item-expired: "&c&l[!] Vật phẩm đã hết hạn"
item-expired-placement: action-bar # action-bar, chat, off
remove-expired-item: true
expired-item-removed: "&cĐã xóa %amount% vật phẩm hết hạn"
unit-format:
  second: "%d giây"
  minute: "%d phút"
  hour: "%d giờ"
  day: "%d ngày"
item-check-interval: 5
